version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies (none for now)"
  build:
    commands:
      - echo "Running app.js"
      - node app.js

artifacts:
  files:
    - '**/*'

